# Generated by Django 5.2.3 on 2025-06-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desg', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='emp_photo')),
            ],
        ),
    ]
